# Generated by Django 5.2 on 2026-03-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_navigationsettings_github_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationsettings',
            options={'verbose_name': 'Navegación'},
        ),
    ]
