# Generated by Django 5.2 on 2026-03-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_navigationsettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationsettings',
            options={'verbose_name': 'Configruación de Navegación'},
        ),
    ]
