# Generated by Django 5.2 on 2026-03-08 19:37

import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name='postpageblogcategory',
#            name='blog_category',
#        ),
        migrations.AlterUniqueTogether(
            name='postpageblogcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postpageblogcategory',
            name='page',
        ),
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Página de Blog'},
        ),
        migrations.AlterModelOptions(
            name='postpage',
            options={'get_latest_by': 'created_at', 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Etiqueta', 'verbose_name_plural': 'Etiquetas'},
        ),
        migrations.AddField(
            model_name='postpage',
            name='content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='postpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='PostPageBlogCategory',
        ),
    ]
