# Generated by Django 5.2 on 2026-03-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpageblogcategory',
            name='blog_category',
        ),
        migrations.AlterUniqueTogether(
            name='postpageblogcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postpageblogcategory',
            name='page',
        ),
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Página de Blog'},
        ),
        migrations.AlterModelOptions(
            name='postpage',
            options={'verbose_name': 'Página de Post'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Etiqueta', 'verbose_name_plural': 'Etiquetas'},
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='PostPageBlogCategory',
        ),
    ]
