# Generated by Django 5.2 on 2026-03-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_hero_text_alter_homepage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Página de Inicio'},
        ),
    ]
